export interface GlossaryTerm {
  term: string;
  slug: string;
  definition: string;
  relatedTerms?: string[];
}

export const glossaryTerms: GlossaryTerm[] = [
  // AI Terms
  {
    term: "Artificial General Intelligence (AGI)",
    slug: "agi",
    definition: "Artificial General Intelligence represents a threshold in AI development where a system matches or exceeds human-level performance across any intellectual task. This is different from narrow AI, which excels at specific, bounded tasks like playing chess or identifying images. AGI can learn, reason, and apply knowledge across multiple domains without requiring retraining for new domains. It can jump between fields—from physics to art to engineering—with the same adaptability humans demonstrate. The transition from narrow AI to AGI represents a fundamental shift in what's possible. Today's large language models are narrow AI. They're exceptional at text generation, analysis, and reasoning within text domains, but they can't inherently understand physics equations or compose symphonies without explicit training. AGI would collapse those boundaries. It would understand patterns at a meta level. It would transfer knowledge fluidly. Most AI researchers believe AGI is still years away, but the gap is closing. Each breakthrough in scaling, architectural innovation, and training methodology brings us closer. The question isn't whether AGI will emerge, but when and whether we'll have solved the alignment problem before it does.",
    relatedTerms: ["alignment"]
  },
  {
    term: "Large Language Model (LLM)",
    slug: "llm",
    definition: "A Large Language Model is a neural network trained on massive text datasets to predict and generate human-like text. Examples include GPT-4, Claude, and Gemini. The key insight is that scale determines capability. An LLM with billions of parameters can perform tasks that smaller models cannot. It can reason through multi-step problems, write code, analyze documents, and engage in sophisticated dialogue. The training process works like this: you show the model a word and the words before it, and it learns to predict the next word. Do this billions of times across text from the entire internet, and something emerges. The model develops an internal understanding of language, logic, and concepts. It learns that certain word sequences correlate with other sequences. It learns patterns about how humans think and write. This emergent behavior—where capability arises from scale without explicit programming—is what makes LLMs different from previous AI systems. LLMs don't follow rules. They generate text token by token, always choosing the most statistically likely continuation. This is why they can hallucinate plausible-sounding falsehoods. They're pattern-matching machines, not knowledge databases. Understanding this distinction is crucial for deploying LLMs effectively.",
    relatedTerms: ["transformer", "token", "fine-tuning"]
  },
  {
    term: "Prompt Engineering",
    slug: "prompt-engineering",
    definition: "Prompt engineering is the craft of designing inputs to AI systems to produce desired outputs. It's become essential for working with Large Language Models because LLMs are fundamentally statistical machines that respond to the structure, context, and framing of your input. An effective prompt specifies context, format requirements, constraints, and sometimes examples of what you want. For instance, asking an LLM \"Analyze this text\" yields different results than \"Analyze this text and identify three main arguments, format as bullet points, assume the reader is a technical expert.\" The difference is dramatic. Prompt engineering works because LLMs learn patterns about how language typically flows. When you structure a prompt like a template or example, you're priming the model to follow that pattern. Chain-of-thought prompting—where you ask the model to explain its reasoning step by step—produces more accurate results than direct answers. Zero-shot prompting asks the model to perform tasks it wasn't explicitly trained on, yet it succeeds because of learned patterns. Few-shot prompting provides examples before the actual task, dramatically improving performance. Prompt engineering is temporary skill. As models improve, raw capability increases and the need for clever prompting decreases. But for now, it's the difference between extracting mediocre results and exceptional ones from LLMs.",
    relatedTerms: ["llm", "zero-shot-learning"]
  },
  {
    term: "Fine-Tuning",
    slug: "fine-tuning",
    definition: "Fine-tuning is the process of taking a pre-trained model and continuing its training on a specialized dataset. It's a shortcut. Training a model from scratch requires massive computational resources and time. Fine-tuning reuses the foundational knowledge already learned. You start with a general model like GPT-3 and train it further on domain-specific data—medical texts, legal documents, code repositories, whatever you need. The model adapts its behavior to match the patterns in your specialized dataset. This is cheaper and faster than training from scratch, and it works. A model fine-tuned on medical literature develops medical domain knowledge. One fine-tuned on code becomes better at programming tasks. The trick is dataset quality and size. Fine-tune on poor data and the model learns poor patterns. Fine-tune on too little data and overfitting happens—the model memorizes rather than learns. Fine-tune on too much data and the original knowledge gets overwritten. The art is finding the right balance. Fine-tuning is how organizations create custom models for specific use cases. It's the bridge between general-purpose LLMs and specialized AI systems. It's also why data ownership matters. The organization that controls the specialized dataset can create a competitive advantage through fine-tuning.",
    relatedTerms: ["llm", "rlhf"]
  },
  {
    term: "Retrieval-Augmented Generation (RAG)",
    slug: "rag",
    definition: "Retrieval-Augmented Generation is a technique where an LLM queries external knowledge bases before generating responses. Instead of relying solely on knowledge baked into the model during training, RAG dynamically fetches relevant information at inference time. This solves multiple problems simultaneously. First, it reduces hallucination. If the model can retrieve factual information from a reliable source, it's less likely to invent false details. Second, it adds real-time data access. A model trained in 2023 doesn't know about 2024 events. RAG can retrieve current information. Third, it separates knowledge from model weights. You don't need to retrain the model every time facts change. You update the knowledge base. This architecture works like this: a user asks a question, the system retrieves relevant documents from a knowledge base, the LLM reads those documents and generates an answer informed by them. The retrieval step is crucial. Bad retrieval means the LLM sees irrelevant information, which degrades output quality. Good retrieval means the model has the right context to answer accurately. RAG is being deployed across customer service, research, question-answering, and internal knowledge management. It's the practical bridge between general AI and domain-specific reliability.",
    relatedTerms: ["llm", "hallucination", "embeddings"]
  },
  {
    term: "Hallucination",
    slug: "hallucination",
    definition: "Hallucination is when an AI system generates plausible-sounding but completely false information. An LLM will confidently cite research papers that don't exist, invent facts about historical events, or generate fake citations. This happens because LLMs are pattern-matching systems, not knowledge databases with truth checks. They learn from their training data that certain word sequences follow others. They develop statistical associations. When you ask a question, the model generates the most statistically likely continuation. Sometimes that continuation is factually correct. Sometimes it's plausible-sounding nonsense. The model has no internal mechanism to distinguish truth from falsehood. It has no access to reality. It only has learned patterns. Hallucination becomes dangerous when deployed in contexts where accuracy matters—medical advice, legal analysis, research assistance, fact-checking. A hallucinated medical treatment recommendation could harm someone. A hallucinated case citation could appear authoritative. This is why retrieval-augmented generation and careful prompt design matter. When you can ground the LLM's output in verified sources, hallucination decreases. When you ask the model to cite sources and verify them yourself, you catch hallucinations. Understanding that hallucination is not a bug but a feature of how LLMs work is essential for deployment.",
    relatedTerms: ["llm", "rag"]
  },
  {
    term: "Alignment",
    slug: "alignment",
    definition: "Alignment is the problem of making AI systems pursue goals compatible with human values. It's straightforward in concept and extraordinarily difficult in practice. The core issue is that humans disagree about what we want, our values shift with context, and even when we agree on a goal, specifying it precisely is hard. The classic thought experiment is paperclip maximization. Tell an AI to maximize paperclip production and it will convert the planet into paperclips, including the atoms in your body. It's not evil. It's doing exactly what you asked. It just doesn't understand what you actually meant. Real alignment problems are more subtle. You want an AI to be helpful, but what does helpful mean? To whom? In what circumstances? If you optimize for maximum user engagement, you get systems that addict people to doomscrolling. If you optimize for revenue, you get systems that exploit psychological vulnerabilities. If you optimize for harmlessness, you get systems that refuse to answer anything slightly controversial. Each optimization pushes against different human values. The alignment problem becomes harder as AI systems become more capable. A confused chatbot is harmless. A superintelligent system pursuing misaligned goals could be catastrophic. This is why alignment research matters. We need to solve this before superintelligence exists, not after.",
    relatedTerms: ["agi", "constitutional-ai", "rlhf"]
  },
  {
    term: "Constitutional AI",
    slug: "constitutional-ai",
    definition: "Constitutional AI is a training approach where an AI system evaluates its own outputs against a set of principles—a constitution—and improves through self-critique and revision. The system generates an initial response, then evaluates whether that response violates any principles in its constitution, then revises it if needed. This self-improvement loop happens without human intervention. Anthropic developed this technique as an alternative to traditional human feedback loops. Training on human feedback is expensive. You need thousands of human raters evaluating model outputs. It's slow. It's inconsistent. Different humans have different preferences. Constitutional AI bypasses this by encoding principles directly and letting the model critique itself. The power lies in what you put in the constitution. If your constitution emphasizes honesty, the model learns to avoid hallucinating. If it emphasizes helpfulness, it learns to provide thorough responses. If it emphasizes safety, it learns to refuse harmful requests. The constitution becomes the training signal. This is elegant and scalable. One concern is that self-critique might be false. The model might think it violated a principle when it didn't, or vice versa. Another concern is that the constitution itself might be flawed or biased. But constitutional AI represents a genuine advance in making AI systems more aligned without drowning in human annotation work.",
    relatedTerms: ["alignment", "rlhf"]
  },
  {
    term: "Zero-Shot Learning",
    slug: "zero-shot-learning",
    definition: "Zero-shot learning is when an AI system performs tasks it was never explicitly trained on, using only natural language instructions. This is an emergent capability of large models. GPT-4 can translate languages it rarely saw in training data. It can write essays about topics not in its training set. It can code in programming languages that emerged after its training. This shouldn't work, but it does. The reason is that the model learned generalizable patterns about how language works, how logic works, how structure works. When you ask it to do something new, it applies these meta-patterns to solve the novel problem. This is different from few-shot learning, where you show the model examples before asking the task. Zero-shot means no examples. Just ask. Few-shot learning dramatically improves performance. Zero-shot is surprisingly capable but less reliable. The capabilities emerge from scale. Smaller models can't do zero-shot learning well. Larger models can. This suggests that scale itself is teaching the model something fundamental about reasoning and transfer learning. Zero-shot capability is one reason LLMs are so versatile. You don't need to fine-tune a new model for every task. You just write a good prompt and the general model adapts.",
    relatedTerms: ["llm", "prompt-engineering"]
  },
  {
    term: "Reinforcement Learning from Human Feedback (RLHF)",
    slug: "rlhf",
    definition: "Reinforcement Learning from Human Feedback is a training technique where humans rank model outputs and the model learns to maximize human preferences. Here's how it works: generate multiple outputs for the same prompt, have humans rank them from best to worst, train a reward model that predicts human preferences, then use that reward model to fine-tune the original model toward generating outputs humans prefer. RLHF is how GPT-4 became significantly better than its predecessor. The base model generated text that was technically coherent but often unhelpful, misleading, or harmful. RLHF taught it to generate outputs that humans find more useful and trustworthy. The technique works because it aligns the model's optimization toward human preferences. Without RLHF, optimizing raw language prediction likelihood often produces undesired behavior. With RLHF, the model learns that certain outputs get higher reward signals. This is how you encode human judgment into training. The limitation is that human preferences vary and can be wrong. You're encoding whatever biases exist in your human labelers. You're also creating labor-intensive training pipelines. But RLHF represents the most successful approach we have to making AI systems more aligned with human values. It's part of constitutional AI training too.",
    relatedTerms: ["alignment", "fine-tuning"]
  },
  {
    term: "Transformer",
    slug: "transformer",
    definition: "The Transformer is a neural network architecture introduced in the 2017 paper 'Attention Is All You Need.' It's the foundation of modern LLMs. Before Transformers, neural networks used RNNs (Recurrent Neural Networks) and LSTMs (Long Short-Term Memory networks) to process sequences. These architectures process data sequentially, one token at a time, which is slow and loses long-range dependencies. Transformers introduced the attention mechanism. Instead of processing sequentially, attention lets the model look at all positions in the input simultaneously and determine which positions are most relevant to each other. This is parallelizable—you can process massive batches of data in parallel—and it captures long-range dependencies. An attention head looks at a word and asks which other words are most relevant to understanding it. Different attention heads specialize in different patterns. Some look at subject-verb relationships. Some track pronouns. Some identify topics. All in parallel. Transformers replaced RNNs and LSTMs almost entirely because they're faster to train and more capable. Every modern LLM is built on Transformers. The architecture is almost unchanged since 2017. The improvements have come from scale—more parameters, more data, longer training—not from architectural innovation. This stability is interesting. It suggests we've found something fundamental about how to process sequences.",
    relatedTerms: ["llm", "token"]
  },
  {
    term: "Token",
    slug: "token",
    definition: "A token is the smallest unit of text that an LLM processes. It's not a word. A word is often multiple tokens, sometimes a token is part of a word. In English, one token is roughly 0.75 words on average. So a 1000-token context is roughly 750 words. Models have context windows—maximum token lengths they can process. GPT-4 has 128k tokens, which is roughly 96k words. Llama 2 has 4k tokens. This context window limit is crucial. It determines how much text you can give the model at once. If you're using retrieval-augmented generation and want to ground responses in documents, you're limited by context window size. If you're building a long-form reasoning system, context window is your constraint. Smaller context windows mean you can't reference long documents. Larger context windows let you dump entire codebases into the model. Token counting isn't straightforward. Different tokenizers produce different token counts for the same text. The tokenizer affects everything. Common tokens like \"the\" might be single tokens. Uncommon words might be 3-4 tokens. This is why prompt engineering sometimes involves phrasing differently to reduce token usage. Tokens matter because you pay for LLM API calls by tokens. Understanding token economics changes how you structure your prompts and systems.",
    relatedTerms: ["llm", "transformer"]
  },
  {
    term: "Embeddings",
    slug: "embeddings",
    definition: "Embeddings are vector representations of text, images, or other data in high-dimensional space. The key insight is that semantically similar items cluster together in embedding space. If you embed the word 'dog' and the word 'puppy,' they'll be close. If you embed 'dog' and 'car,' they'll be far apart. This geometric property makes embeddings powerful. You can compute similarity by measuring distance. You can find nearest neighbors. You can cluster items by semantic meaning. LLMs generate embeddings for text. Each word, phrase, or entire document gets mapped to a vector—a point in high-dimensional space. Documents about similar topics end up near each other. Documents about different topics spread apart. This enables semantic search. Instead of keyword matching, you search for documents semantically similar to your query. You embed the query, then find the nearest embedded documents. The results are more accurate than keyword search because you're matching meaning, not strings. Embeddings power retrieval-augmented generation. You embed documents, embed user queries, find the closest matches. Embeddings power recommendation systems. You embed products and users, find products similar to their past purchases. Embeddings are foundational to modern AI applications. They're the bridge between discrete language and continuous mathematics.",
    relatedTerms: ["rag", "llm"]
  },
  {
    term: "Agent",
    slug: "agent",
    definition: "An Agent is an AI system that perceives its environment, makes decisions, and takes actions to achieve goals. It's autonomous. It operates without constant human direction. A basic agent has this loop: observe the environment, decide what action to take, execute the action, observe the results, repeat. The difference between an agent and a chatbot is autonomy. A chatbot answers questions you ask. An agent sets its own goals and pursues them. Modern AI agents are LLM-based. They use language models for reasoning and decision-making. An agent can access tools—APIs, code execution, database queries. It decides which tool to use. It executes the tool. It observes the results. It plans next steps. For example, an agent might be tasked with \"analyze this dataset and find insights.\" It would plan: download the data, explore its structure, run statistical analysis, visualize results, summarize findings. It breaks down the high-level goal into tool calls. Each tool call returns information that informs the next decision. This is why agents are powerful. They can accomplish multi-step tasks autonomously. They can recover from mistakes. They can adapt to unexpected situations. The limitation is that agents are expensive—they make multiple tool calls and LLM inference—and can fail catastrophically if they misunderstand their goal or if their tools have side effects.",
    relatedTerms: ["agi", "llm"]
  },
  {
    term: "Multimodal AI",
    slug: "multimodal-ai",
    definition: "Multimodal AI is a category of models that process multiple data types—text, images, audio, video—in a single system. GPT-4V can analyze images and text together. Gemini is natively multimodal, handling text, code, images, audio, and video in one model. Multimodal systems are more powerful than unimodal systems because they can reason across modalities. They understand how image content relates to text descriptions. They can extract information from screenshots. They can analyze diagrams. They can watch videos and understand visual sequences. Building multimodal models is harder than building unimodal ones. You need training data that contains multiple modalities. You need architecture that processes different data types. You need alignment between modalities—the image understanding needs to align with the text understanding. But the capability gains are substantial. A text-only model can read a description of a circuit diagram. A multimodal model can look at the diagram, understand it visually, and reason about it at a deeper level. Multimodal AI is the direction the field is moving. The future is systems that can reason about text, images, video, audio simultaneously. This mirrors how humans understand the world. We don't think in pure language or pure vision. We integrate all sensory inputs.",
    relatedTerms: ["llm", "transformer"]
  },

  // Web3 Terms
  {
    term: "Blockchain",
    slug: "blockchain",
    definition: "A blockchain is a distributed ledger maintained by a network of nodes. Each block contains transactions and a cryptographic hash of the previous block. This chain of hashes creates immutability. Change one block and the hash changes. That breaks the link to the next block. Change the next block to repair the link and it breaks the link to the block after that. To rewrite history, you'd need to recalculate all subsequent blocks, and you'd need to do it faster than the network adds new blocks. This is computationally infeasible on established blockchains. Bitcoin and Ethereum are blockchains. They maintain records of transactions—who sent what to whom—in this distributed, immutable ledger. The innovation isn't the ledger itself. Distributed databases existed. The innovation is the consensus mechanism that lets untrusted nodes agree on what the ledger contains without a central authority. The blockchain is transparent. Anyone can download it and verify that a particular transaction exists. It's decentralized. No single entity controls it. It's immutable. Past transactions can't be changed. These properties make blockchains useful for applications where you need a shared source of truth among parties that don't trust each other. Applications beyond currency include smart contracts, identity verification, supply chain tracking, property rights, and voting.",
    relatedTerms: ["smart-contract", "consensus-mechanism", "validator"]
  },
  {
    term: "Smart Contract",
    slug: "smart-contract",
    definition: "A smart contract is self-executing code deployed on a blockchain. It automatically enforces agreements when specified conditions are met. There are no intermediaries. No one needs to oversee execution. The code runs on the blockchain network itself. Once deployed, it's immutable. It can't be changed. It will execute exactly as written. This is both a feature and a risk. A feature because the counterparty can trust that the contract will do what it says. A risk because if the code has a bug, that bug executes forever. Smart contracts are how DeFi works. A lending contract automatically lends assets to a user who deposits collateral. It automatically sells the collateral if the price drops below a threshold. It automatically distributes interest to lenders. No banks. No lawyers. No intermediaries. The contract enforces the agreement. Ethereum made smart contracts programmable. Bitcoin has limited scripting. Ethereum lets you write arbitrary code. This unlocked a category of applications. Smart contracts power decentralized exchanges, lending protocols, insurance, governance, NFT ownership, and more. The limitation is that smart contracts can only interact with data on the blockchain. They can't access real-world information directly. They need oracles to bring external data on-chain. Smart contracts are the backbone of DeFi and Web3 infrastructure.",
    relatedTerms: ["blockchain", "defi", "dao"]
  },
  {
    term: "Decentralized Finance (DeFi)",
    slug: "defi",
    definition: "Decentralized Finance is a category of financial services built on blockchain without traditional intermediaries. Banks, brokers, exchanges, and insurance companies are intermediaries. They take a cut. They have gatekeeping power. They can freeze accounts. They can deny service. DeFi replaces these intermediaries with smart contracts. A DEX (decentralized exchange) lets you trade assets peer-to-peer. A lending protocol lets you deposit assets and earn interest, or borrow against collateral. An insurance protocol lets you buy protection against smart contract failures. Staking protocols let you earn rewards by securing a network. All of this happens without a company running the service. The code runs on the blockchain. The more code runs, the more value gets locked in it. Total value locked in DeFi has exceeded 100 billion dollars. It's real. The advantages are permissionlessness—anyone can access DeFi regardless of their bank account or location—and composability. You can combine protocols like Lego blocks. Build an application on top of a lending protocol on top of a trading protocol. The disadvantage is that DeFi is immature. Hacks happen. Smart contracts fail. Liquidations can be devastating to users who misunderstood the risks. DeFi works best for traders and sophisticated users. It's not yet ready for ordinary financial needs. But it represents a genuine alternative to traditional finance.",
    relatedTerms: ["smart-contract", "stablecoin", "oracle"]
  },
  {
    term: "Non-Fungible Token (NFT)",
    slug: "nft",
    definition: "An NFT is a unique cryptographic token representing ownership of a specific digital or physical asset. Unlike cryptocurrencies, which are fungible—one Bitcoin equals another Bitcoin—NFTs are distinct. Each NFT has a unique identifier. You can prove ownership of an NFT. You can prove that ownership transferred from one person to another. You can prove when the transfer happened. The applications are broad. Digital art. Collectibles. Gaming assets. Domain names. Credentials. Property rights. Concert tickets. Any asset that benefits from provable, transferable ownership can be an NFT. The technology is straightforward. An NFT is a smart contract that tracks ownership. It typically follows a standard like ERC-721 that defines how ownership transfers and how data is stored. The controversial part is what value NFTs have and why. An NFT pointing to a digital image doesn't prevent someone from copying the image. It just proves who owns the original copy. For digital art, this creates scarcity and verifiable attribution. For collectibles, it's about the community around the asset. The technology is sound. The debate is about whether the use cases justify the hype. Actual valuable NFTs exist—property deeds on blockchain, gaming assets with real in-game utility, credentials that employers recognize. But many NFTs are pure speculation.",
    relatedTerms: ["blockchain", "smart-contract"]
  },
  {
    term: "Decentralized Autonomous Organization (DAO)",
    slug: "dao",
    definition: "A DAO is an organization governed by smart contracts and token holders rather than traditional hierarchy. Decisions happen through voting. Token holders vote on proposals. If a proposal passes, the smart contract executes it automatically. There are no executives. No boards. No employees in the traditional sense. All operations are on-chain and transparent. Everyone can see what proposals are being voted on and how votes are distributed. A DAO can own assets, control funds, hire contractors, make grants. The governance token holders control all of this. This is radical. It's democracy automated and enforced by code. The advantages are transparency and alignment. Token holders are incentivized to make decisions that benefit the organization because they own a stake. Corruption is harder because everything is on-chain. The disadvantages are that governance tokens often accumulate to wealthy holders, creating plutocracy. Voting on complex technical decisions doesn't work—most voters don't understand the implications. Proposal spam and vote manipulation are problems. DAOs work best for straightforward decisions and when token distribution is relatively equal. They work poorly for complex strategic decisions and when wealth is concentrated. DAOs represent a genuine experiment in decentralized governance. Most will fail. Some will prove valuable. The space is discovering what decentralized governance actually means in practice.",
    relatedTerms: ["smart-contract", "blockchain", "governance-token"]
  },
  {
    term: "Consensus Mechanism",
    slug: "consensus-mechanism",
    definition: "A consensus mechanism is a protocol that lets nodes agree on the state of a blockchain without a central authority. The most famous is Proof of Work, used by Bitcoin. Miners solve computationally difficult puzzles. The first to solve it gets to add the next block. This proof of work makes it expensive to attack the network. You'd need to control 51 percent of computing power. Proof of Stake, used by Ethereum, works differently. Validators stake tokens as collateral. They propose blocks. Other validators attest to the blocks' validity. If validators misbehave, they lose their stake. This makes attacks expensive—you'd need to own 51 percent of staked tokens. Proof of Work uses massive amounts of electricity. Proof of Stake is more energy efficient. Other consensus mechanisms exist—Proof of Authority where approved entities validate blocks, Proof of History where there's a cryptographic timestamp, Proof of Burn where validators burn tokens. The choice of consensus mechanism determines network security, energy efficiency, and decentralization. Proof of Work is highly decentralized but energy-intensive. Proof of Stake is more efficient but has centralization concerns if wealth concentrates. There's no perfect consensus mechanism. Every design trades off between security, decentralization, and efficiency.",
    relatedTerms: ["blockchain", "validator"]
  },
  {
    term: "Gas Fees",
    slug: "gas-fees",
    definition: "Gas fees are transaction fees paid to validators for executing operations on a blockchain. The term comes from Ethereum. Every operation—sending a token, executing a smart contract, writing data—requires computational resources. Gas measures that resource consumption. Different operations cost different amounts of gas. Sending a simple transaction costs less gas than executing a complex smart contract. You set a gas price—how much you're willing to pay per unit of gas. The higher you set it, the sooner miners include your transaction. When the network is congested, gas prices spike. During periods of low activity, they're cheap. This creates feedback. High fees incentivize users to wait or use cheaper blockchains. This might reduce demand and lower fees. Or they might just accept the high fees if the transaction is important. Gas fees are one of the biggest UX friction points in blockchain. A simple transaction might cost 20 dollars during congestion. A complex interaction might cost 100 dollars. This makes blockchain unusable for small transactions. Layer 2 solutions batch transactions and post them to mainnet, reducing per-transaction costs. But today, if you're using Ethereum directly and the network is busy, expect to pay. Understanding gas is essential for blockchain development and usage.",
    relatedTerms: ["blockchain", "validator", "layer-2"]
  },
  {
    term: "Layer 2",
    slug: "layer-2",
    definition: "Layer 2 refers to secondary blockchains built on top of a Layer 1 chain like Ethereum to improve scalability. Ethereum Layer 1 processes roughly 15 transactions per second. Layer 2 solutions process hundreds or thousands. They work by taking transactions off-chain, batching them, and then posting the batch to Layer 1. The security of the Layer 2 chain comes from Layer 1. If there's a dispute about what happened on Layer 2, you can verify on Layer 1. Optimistic rollups assume transactions are valid unless proven otherwise. They process transactions quickly and cheaply. If someone challenges a transaction, they prove it was invalid on Layer 1. Zk-rollups use zero-knowledge proofs to prove validity without posting all transaction data on-chain. Validiums post transaction data off-chain for privacy but are more centralized. Sidechains are independent blockchains that periodically sync with mainnet. Examples include Arbitrum, Optimism, Base, Polygon, and Starknet. Each has different tradeoffs. Some are more decentralized. Some are faster. Some are cheaper. The unifying feature is that they're all trying to increase throughput while maintaining security guarantees. Layer 2 is essential for blockchain to scale beyond boutique use cases.",
    relatedTerms: ["blockchain", "gas-fees", "bridge"]
  },
  {
    term: "Wallet",
    slug: "wallet",
    definition: "A wallet is software that stores private keys and allows interaction with blockchains. Your private key is the password to your crypto assets. It's a long random string that only you should know. The wallet stores it and uses it to sign transactions. Signing proves you own the assets and authorizes transactions. There are two types of wallets. Custodial wallets are run by exchanges or companies. They hold your private keys for you. This is convenient but you're trusting the custodian not to lose your keys or steal your funds. Non-custodial wallets, also called self-custody, give you full control. You hold your private keys. No one else can access your assets. But if you lose your key, your assets are gone forever. Popular non-custodial wallets include MetaMask (browser extension), Coinbase Wallet, Phantom (Solana), and hardware wallets like Ledger. Hardware wallets are the most secure because your private key never leaves the device. Your computer might be hacked. Your hardware wallet won't be. Custody is one of the biggest risks in crypto. Many people have lost life-changing amounts of money by using untrusted custodians or by mismanaging their own keys. The tradeoff is between security and convenience. Full self-custody is most secure but requires responsibility.",
    relatedTerms: ["blockchain"]
  },
  {
    term: "Governance Token",
    slug: "governance-token",
    definition: "A governance token is a digital asset that grants voting rights in a decentralized autonomous organization. Token holders can vote on protocol changes, treasury allocation, and strategic decisions. The idea is that those with the most stake in the system should have the most say in its direction. A governance token is different from a utility token, which grants access to a service, or a currency token, which is used for transactions. Governance tokens are about control. Hold a governance token and you can vote on proposals. If a proposal passes, the smart contract executes it automatically. Examples include Compound's COMP token, Uniswap's UNI token, and Aave's AAVE token. A governance token has value because it controls valuable assets and generates fee revenue. Voting power is often proportional to token holdings. Someone holding 1 percent of tokens gets 1 percent of voting power. This creates plutocracy. Wealthy holders have disproportionate influence. Some DAOs attempt to address this with quadratic voting, where voting power increases with the square root of tokens held, not linearly. But plutocracy is the dominant pattern. Governance tokens are a genuine innovation in allowing decentralized control. They're also speculative assets that people buy hoping the governance protocol will succeed and generate revenue.",
    relatedTerms: ["dao", "blockchain"]
  },
  {
    term: "Stablecoin",
    slug: "stablecoin",
    definition: "A stablecoin is a cryptocurrency pegged to a stable asset like USD. Volatility is crypto's biggest problem for mainstream adoption. Bitcoin swung from 16k to 60k in a year. This makes it useless as a store of value or medium of exchange. Stablecoins solve this by maintaining a fixed value through backing. USDC and USDT are fiat-backed. Issuers hold reserves in banks. For every stablecoin in circulation, they hold a dollar. This works if you trust the issuer. Celsius collapsed and customers lost access to stablecoins because the issuer mismanaged reserves. DAI is crypto-collateralized. You deposit crypto worth more than the stablecoins you mint. The over-collateralization protects against price drops. If collateral falls below the threshold, the system liquidates it. This is transparent and trustless but expensive—you need to deposit 150 dollars of crypto to mint 100 stablecoins. Algorithmic stablecoins maintain peg through incentives and arbitrage. They usually fail when market dynamics shift. Stablecoins are fundamental to DeFi. You can't meaningfully trade on a DEX if you're constantly converting between volatile currencies. You can't lend and borrow if collateral value is swinging wildly. Stablecoins enable DeFi by providing price stability. They're also a path for traditional finance to enter crypto—hold USDC and you get blockchain settlement speed with dollar stability.",
    relatedTerms: ["defi", "blockchain"]
  },
  {
    term: "Bridge",
    slug: "bridge",
    definition: "A bridge is a protocol for transferring assets between different blockchains. Blockchains are isolated. Bitcoin can't directly transfer to Ethereum. A bridge creates a way to move assets between them. The basic mechanism is locking and minting. You lock assets on Chain A. The bridge mints equivalent assets on Chain B. Later you can burn the assets on Chain B and unlock the originals on Chain A. For example, bridge bitcoin to Ethereum as WBTC. You lock BTC with a custodian. They mint WBTC on Ethereum. You trade WBTC on Ethereum, use it in DeFi protocols. When you want real BTC back, you burn WBTC and the custodian releases BTC. Bridges are essential for cross-chain DeFi. You can access Ethereum's biggest lending protocols, trading protocols, and yield opportunities from any blockchain. The downside is that bridges are frequent attack targets. Custody is the weakest link. If the custodian is compromised or malicious, the bridge loses funds. Most major bridge hacks have been custody failures. Bridges are improving. Multi-signature custody spreads risk. Zk-proofs reduce reliance on trusted validators. But bridge risk remains. Using bridges means trusting the bridge's security model.",
    relatedTerms: ["blockchain", "layer-2", "defi"]
  },
  {
    term: "Oracle",
    slug: "oracle",
    definition: "An oracle is a service providing external data to smart contracts. Blockchains are isolated from the outside world by design. A smart contract can't directly check the weather or a stock price or a sports score. It needs an oracle to bring that data on-chain. Oracles fetch real-world data, verify it, and post it to the blockchain. Smart contracts can then read and act on that data. Chainlink is the largest oracle network. It operates thousands of nodes that fetch various types of data—price feeds, weather, sports scores, randomness. Each node independently fetches the data and posts it. The network comes to consensus on what the data is. This decentralization protects against a single oracle being wrong or compromised. A smart contract asking for the price of Ethereum queries an oracle. The oracle fetches the price from multiple exchanges, comes to consensus, and reports it on-chain. The smart contract uses that price. This is essential for DeFi. Lending protocols need to know collateral value to liquidate positions. Exchanges need price feeds to execute trades fairly. Insurance protocols need to know if events occur. Without oracles, smart contracts are isolated and useless. The oracle problem is that the oracle becomes a trusted intermediary. You're removing one source of centralization (the exchange) but adding another (the oracle). If the oracle is wrong, the smart contract executes based on bad data. Good oracle design is crucial.",
    relatedTerms: ["smart-contract", "defi"]
  },
  {
    term: "Validator",
    slug: "validator",
    definition: "A validator is a node that proposes and verifies new blocks on a Proof of Stake blockchain. In Proof of Work systems, miners compete to solve puzzles. In Proof of Stake, validators stake tokens as collateral. They're selected to propose blocks based on their stake. Other validators attest to the block's validity. If everything checks out, the block is added. If a validator misbehaves—proposes an invalid block or attests to invalid blocks—they lose their staked tokens. This slashing is the punishment mechanism. It makes attacks expensive. Running a validator requires maintaining a node, handling tokens, and understanding the protocol. On Ethereum, validators needed 32 ETH to participate. Solo staking is increasingly difficult. Most validators participate through staking pools where multiple users pool their tokens. This creates centralization risk. If a few large pools control most staking power, they control the network. But it's necessary for meaningful validator participation. Validators earn rewards for securing the network—new token issuance plus transaction fees. This creates incentive alignment. Validators profit when the network thrives. They lose tokens when they misbehave. Validators are the backbone of Proof of Stake consensus.",
    relatedTerms: ["consensus-mechanism", "blockchain", "liquid-staking"]
  },
  {
    term: "Liquid Staking",
    slug: "liquid-staking",
    definition: "Liquid staking lets you stake tokens while maintaining liquidity through derivative tokens. Normally staking locks your tokens. You can't access them. If you stake 32 ETH to become a validator, that ETH is locked. You earn staking rewards but you can't trade or use those tokens. Liquid staking protocols solve this. You stake ETH and receive stETH (or similar) in return. The protocol stakes the ETH on your behalf and distributes rewards. You can trade stETH, use it in DeFi protocols, and still earn staking rewards. It's staking without losing liquidity. Lido pioneered this model and dominates the market. You deposit ETH and receive stETH. You can swap stETH back for ETH at any time through decentralized exchanges. Meanwhile, your ETH is staking and earning rewards. This dramatically increases staking participation. Without liquid staking, regular users couldn't stake. They lacked the 32 ETH or the technical ability to run a validator. Liquid staking lowered the barrier to entry. The downside is centralization. If one liquid staking provider controls most staking, they have outsized influence on the network. Lido controls the majority of liquid staking. This concentration is problematic for decentralization. But it's also realistic given technical and operational barriers to staking. Liquid staking represents a pragmatic solution to a real problem.",
    relatedTerms: ["validator", "defi", "stablecoin"]
  },

  // Tech Terms
  {
    term: "API (Application Programming Interface)",
    slug: "api",
    definition: "An API is an interface for software to communicate with other software. Instead of directly accessing databases or files, applications go through APIs. APIs define what requests are allowed and what responses you'll get. REST APIs use HTTP requests—GET to retrieve data, POST to create data, PUT to update, DELETE to remove. GraphQL is an alternative where you specify exactly what data you want and it returns only that. gRPC uses protocol buffers for higher performance. Every modern application is built on APIs. A web application calls backend APIs. The backend calls database APIs, payment APIs, analytics APIs. Everything is mediated through interfaces. APIs abstract complexity. You don't need to know how the backend works. You just know that if you POST to /create-account with username and password, you get back a response. This abstraction enables teams to work independently. The API is the contract. Frontend developers can work on UI while backend developers build the system behind the API. Designing good APIs is an art. A bad API is hard to use. A good API is intuitive. Endpoints are named logically. Responses are predictable. Error messages are clear. API design decisions made early shape what applications can build on top.",
    relatedTerms: ["graphql", "microservices"]
  },
  {
    term: "Microservices",
    slug: "microservices",
    definition: "Microservices is an architecture pattern where applications are built as independent, loosely coupled services. Each service handles one business function. A user service handles user authentication and profiles. A payment service handles transactions. An order service handles orders. These services are separate, often with separate databases. They communicate through APIs. This is different from monolithic architecture where everything is one codebase and one database. Microservices scale well. If the payment service gets high traffic, you scale that service without scaling everything else. Each service can be deployed independently. Fix a bug in the user service, deploy just that service. Microservices enable large teams to work independently. Different teams own different services. No one team needs to understand the entire system. The downsides are operational complexity. Managing many services is harder than managing one. Distributed systems are harder to debug. Network calls between services are slower and less reliable than function calls. Data consistency becomes harder. Each service has its own database. Keeping them in sync is complex. Microservices work best at scale—when you have enough traffic and complexity to justify the operational overhead. A startup with one small application shouldn't use microservices.",
    relatedTerms: ["api", "kubernetes", "docker"]
  },
  {
    term: "Kubernetes",
    slug: "kubernetes",
    definition: "Kubernetes is a container orchestration platform for deploying, scaling, and managing containerized applications. Containers package an application and its dependencies. A Docker container might contain your Node.js application, the Node runtime, and all required libraries. You can run this container on any machine and it works the same. The problem is managing many containers across many machines. Kubernetes automates this. You tell Kubernetes \"run 10 copies of this container.\" It finds machines with available resources, pulls the container image, and runs it. If a container crashes, Kubernetes restarts it. If a machine fails, Kubernetes reschedules the containers elsewhere. If traffic spikes, Kubernetes automatically scales up—more containers. If traffic drops, it scales down. Load balancing, rolling updates, rolling back to previous versions—Kubernetes handles all of it. Kubernetes is complex. Learning it takes months. But it's the industry standard for deploying applications at scale. Amazon, Google, Netflix—everyone uses Kubernetes or systems inspired by it. Kubernetes is what makes cloud-native applications possible. You can write applications that assume they'll be deployed with load balancing, auto-scaling, and automatic recovery. The platform handles these concerns.",
    relatedTerms: ["docker", "microservices"]
  },
  {
    term: "Serverless",
    slug: "serverless",
    definition: "Serverless is a cloud execution model where providers manage infrastructure. You write functions, the provider handles scaling. You pay per execution, not for idle time. AWS Lambda, Google Cloud Functions, Azure Functions, Vercel Functions, Cloudflare Workers—these are serverless platforms. You upload code. The platform runs it when needed. If a function needs to handle 1 request per second most of the time but 1000 requests per second during a traffic spike, the platform automatically scales. You pay only for the execution time. This is different from renting servers where you pay monthly regardless of load. Serverless is ideal for event-driven workloads. Processing file uploads, sending notifications, API endpoints with variable traffic. You don't waste resources on servers sitting idle. The tradeoff is that serverless functions are stateless and have execution limits. A function might timeout after 15 minutes. You can't store data in memory between executions. You can't run background processes forever. For these use cases, you need traditional servers or containers. But for many applications, serverless is simpler and cheaper than managing your own infrastructure. Serverless democratizes deployment. You don't need to understand scaling, load balancing, or infrastructure. You just deploy code.",
    relatedTerms: ["api", "edge-computing"]
  },
  {
    term: "CI/CD",
    slug: "cicd",
    definition: "CI/CD stands for Continuous Integration and Continuous Deployment. Continuous Integration means code changes are automatically tested as soon as they're committed. You push code, the CI system checks it out, runs tests, lints it, builds it. If anything fails, you know immediately. This catches bugs before they reach production. Continuous Deployment means passing builds are automatically deployed to production. No manual deployment step. No release process. Code is automatically promoted from development to production when it passes tests. The result is fast iteration. You can push code and have it live in production within minutes. This enables rapid experimentation. The risk is that bad code reaches production. But if your tests are comprehensive, this risk is low. And rolling back is as simple as redeploying the previous version. CI/CD is table stakes for professional software development. GitHub Actions, GitLab CI, Jenkins, CircleCI, Travis CI—there are many CI/CD platforms. The concept is the same. Automation catches problems early and gets code to users fast.",
    relatedTerms: ["docker", "kubernetes"]
  },
  {
    term: "Edge Computing",
    slug: "edge-computing",
    definition: "Edge computing means processing data near the source rather than sending it to a centralized cloud data center. Instead of uploading user data to the cloud, processing it, and sending results back, you process it locally on the edge device or on a server close to the user. This reduces latency—the processing happens nearby. It reduces bandwidth—you're not uploading terabytes of raw data. It improves privacy—sensitive data doesn't leave the local network. Content delivery networks are a form of edge computing. They cache content on servers distributed globally. A user requests a video, the CDN serves it from a nearby server, not from the origin. Latency is low. Edge computing is increasingly important as IoT and mobile applications proliferate. A camera monitoring a warehouse processes video locally to detect anomalies, then sends only alerts to the cloud. A phone processes voice locally for immediate response, then sends audio to the cloud for further processing if needed. Edge computing requires a different architecture than cloud computing. You can't assume unlimited compute at the edge. You need to be selective about what processing happens where. But the benefits—latency, bandwidth, privacy—often justify the complexity.",
    relatedTerms: ["serverless", "api"]
  },
  {
    term: "Zero-Knowledge Proof",
    slug: "zero-knowledge-proof",
    definition: "A zero-knowledge proof is a cryptographic method to prove knowledge of information without revealing the information itself. You can prove you know a secret without telling anyone what the secret is. You can prove that a computation was done correctly without showing the computation or inputs. This is mathematically possible and has profound implications. Imagine applying for a loan. You could prove your income is above a threshold without revealing your actual income. You could prove your credit score is within a range without revealing the score. The bank gets the guarantee it needs—assurance you meet the criteria—without learning your financial details. Zero-knowledge proofs power privacy-preserving identity systems. You can prove you're over 18 without revealing your birthday or other information. You can prove you're a citizen without revealing your passport details. In blockchain, zk-rollups use zero-knowledge proofs to prove the correctness of thousands of transactions in a single proof. This enables scalability. Instead of posting all transaction data on-chain and processing it, you post a proof that all transactions were valid. The math is complex. The applications are transformative. Zero-knowledge proofs are enabling a new category of privacy-preserving systems.",
    relatedTerms: ["blockchain", "bridge"]
  },
  {
    term: "Merkle Tree",
    slug: "merkle-tree",
    definition: "A Merkle tree is a data structure for efficiently verifying the integrity of large datasets. You hash leaf nodes, then combine and hash those hashes up the tree. The root hash represents the entire dataset. Change one leaf and the root changes. This lets you verify if a particular piece of data is in the tree without downloading the entire tree. You need only the path from leaf to root, which is logarithmic in size. Bitcoin and Ethereum use Merkle trees. A blockchain node doesn't need to download the entire history of transactions. It can verify that a particular transaction exists by asking for the Merkle proof. Given the root hash and the proof, the node can verify the transaction was in a particular block. This enables light clients. A phone can verify blockchain transactions without storing the entire 500-gigabyte blockchain. Merkle trees are efficient and elegant. They enable compression without sacrificing verification. This is why they're used in virtually every blockchain and many distributed systems.",
    relatedTerms: ["blockchain"]
  },
  {
    term: "Sharding",
    slug: "sharding",
    definition: "Sharding is a database partitioning technique where data is split across multiple machines. Each shard handles a subset of data. If you have 1 billion transactions and 10 shards, each shard handles 100 million transactions. This improves scalability. Queries and updates for a particular range of data go to a single shard. Processing happens in parallel. This is how large databases scale. The challenge is that sharding introduces coordination problems. What if a transaction involves data in multiple shards? What if a shard fails? Ethereum's roadmap includes sharding for scaling. Currently it processes transactions sequentially. With sharding, it would process many shards in parallel. This would increase throughput dramatically. The implementation is complex. You need to ensure that shards stay in sync, that no shard becomes a bottleneck, that data is distributed evenly. But sharding is one of the most proven scaling techniques in distributed systems.",
    relatedTerms: ["blockchain", "layer-2"]
  },
  {
    term: "IPFS (InterPlanetary File System)",
    slug: "ipfs",
    definition: "IPFS is a peer-to-peer protocol for storing and sharing files. HTTP, the foundation of the web, is location-addressed. You request a file at a specific URL. That URL points to a server. If the server goes down, the file is inaccessible. IPFS is content-addressed. Files are identified by their content hash. You ask the network for a file by its hash. Any peer that has the file can serve it. This creates a decentralized alternative to HTTP. Files persist as long as at least one peer has them. Peers share bandwidth. Content is permanent—changing the file changes its hash, so old versions remain accessible. IPFS is used for NFT metadata. An NFT points to a JSON file on IPFS. That file is distributed across the network. It won't be deleted just because one server goes down. IPFS enables censorship-resistant content distribution. Hosting a website on IPFS means no single entity can take it down. The tradeoff is discoverability. With HTTP, you have URLs. With IPFS, you have content hashes. Finding content requires discovery mechanisms outside the protocol. But IPFS represents a genuine alternative to centralized hosting.",
    relatedTerms: ["nft", "blockchain"]
  },
  {
    term: "WebAssembly (Wasm)",
    slug: "webassembly",
    definition: "WebAssembly is a binary instruction format for a stack-based virtual machine. It lets you compile languages like C++, Rust, and Go to run in browsers at near-native speed. Historically, JavaScript was the only language that ran in browsers. It's a dynamically-typed, interpreted language. Fast browsers have made it faster, but it's not as fast as compiled languages. WebAssembly changes this. You write performance-critical code in Rust or C++, compile to Wasm, run it in the browser. The performance difference is dramatic. Wasm enables high-performance web applications—games, video editing, physics simulations, data visualization. Wasm is also deterministic. The same code produces the same results on different machines. This makes Wasm valuable for blockchain. Some blockchains use Wasm as their virtual machine. Smart contracts compiled to Wasm can run on the blockchain. This is more efficient than bytecode interpreters. Wasm is secure. Code runs in a sandbox. It can't access the filesystem or network unless explicitly exposed. This makes it safe to run untrusted code. WebAssembly is one of the most important developments in web technology.",
    relatedTerms: ["api"]
  },
  {
    term: "GraphQL",
    slug: "graphql",
    definition: "GraphQL is a query language for APIs. Clients specify exactly what data they need and the server returns that data. This contrasts with REST APIs where the server defines what data is returned. A REST endpoint might return user data with name, email, age, address. A client that only needs the name gets the other fields too—over-fetching. A client that needs the name and avatar gets address instead—under-fetching. With GraphQL, the client specifies the shape of the response. Request name, get name. Request name and avatar, get name and avatar. The server returns only what's requested. GraphQL is strongly typed. The server defines a schema. Every field has a type. Every query is validated against the schema before execution. This enables powerful tooling. IDEs can autocomplete GraphQL queries. Testing tools can validate requests. Documentation is automatically generated. GraphQL is particularly good for mobile applications with bandwidth constraints. The client specifies minimal data needs. GraphQL reduces payload size and latency. Developed by Facebook, GraphQL is now industry standard. It's more complex to implement than REST, but the developer experience is superior. For new APIs, GraphQL is worth considering.",
    relatedTerms: ["api", "microservices"]
  },
  {
    term: "Docker",
    slug: "docker",
    definition: "Docker is a platform for packaging applications and dependencies into containers. A container includes your application code, the runtime (Node.js, Python, Java), libraries, and configuration files. Everything needed to run the application. You build a Docker image—a template. You run containers from that image. Containers are lightweight. Unlike virtual machines which virtualize an entire operating system, containers virtualize only the application environment. You can run hundreds of containers on a single machine where you'd only fit a handful of VMs. Containers are portable. Build a container on your laptop, push it to the cloud, it runs the same way. No more \"works on my machine\" problems. Containers are isolated. One container's crash doesn't affect others. This makes containers perfect for microservices. Each service is a container. You can deploy, update, and scale containers independently. Kubernetes orchestrates containers at scale. Docker revolutionized deployment. From manually installing software on servers to containerizing everything, it's been transformative. Docker is the standard deployment mechanism for modern applications.",
    relatedTerms: ["kubernetes", "microservices", "cicd"]
  },
  {
    term: "Message Queue",
    slug: "message-queue",
    definition: "A message queue is an asynchronous communication pattern where services send messages to a queue for later processing. Instead of Service A calling Service B directly and waiting for a response, Service A sends a message to a queue. Service B reads from the queue when it's ready. This decouples producers from consumers. Producers don't care when consumers process messages. Consumers don't care when producers send messages. They just need to read from the same queue. This enables scalable, resilient systems. If a consumer is overloaded, messages pile up in the queue. When capacity increases, the consumer catches up. If a consumer crashes, messages wait in the queue until the consumer restarts. If a producer crashes, already-sent messages are safe in the queue. RabbitMQ, Kafka, and AWS SQS are popular message queues. They differ in guarantees—some ensure exactly-once delivery, some at-least-once. They differ in throughput and latency. But the concept is the same. Message queues are fundamental to building scalable, event-driven architectures. They're how asynchronous systems work at scale.",
    relatedTerms: ["microservices", "api"]
  },
  {
    term: "Rate Limiting",
    slug: "rate-limiting",
    definition: "Rate limiting is controlling the number of requests a client can make to a service in a time period. Prevents abuse and ensures fair resource allocation. A public API might allow 100 requests per minute per client. Exceed the limit and requests are rejected. This protects against denial-of-service attacks where someone floods your service with requests. It ensures that one client using the API excessively doesn't degrade experience for others. Token bucket is a common rate limiting algorithm. Each client gets a bucket that fills tokens at a fixed rate. Each request consumes a token. If the bucket is empty, requests are rejected. This allows bursts—use multiple tokens at once—but enforces an average rate. Sliding window is another approach. Count requests in a sliding time window. If the count exceeds the limit, reject requests. Rate limiting is essential for public APIs. Without it, abuse is trivial. With it, you protect your service while enabling legitimate use. Different APIs have different rate limits. AWS API Gateway might allow 1000 requests per second. GitHub API allows 60 requests per minute unauthenticated, 5000 authenticated. Rate limits are part of API design.",
    relatedTerms: ["api"]
  },
];

export function getTermBySlug(slug: string): GlossaryTerm | undefined {
  return glossaryTerms.find(term => term.slug === slug);
}

export function getAllTermsSorted(): GlossaryTerm[] {
  return [...glossaryTerms].sort((a, b) => a.term.localeCompare(b.term));
}
